### ISSUE TITLE
PDF generation broken in 2.2b3

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3668]
I am using OS 2.2b3. I cannot
- export the agenda list as PDF
- export the election list as PDF
- generate a ballot paper as PDF

Only exporting the motion list as PDF works.

This is a mustfix in my opinion because especially that I could not generate ballot papers was a nightmare. i had to create one just in time using Excel.

**Comment by emanuelschuetze** [comment]
ballot paper is fixed in #3660. Rest works for me in current master. 
@donovaly Please retest with new test version.

**Comment by donovaly** [comment]
The ballot paper PDF is not fixed, the other things work now.

Instead of a ballot PDF I get now only an empty PDF.

**Comment by emanuelschuetze** [comment]
I can't confirm this. Please retest - also with a new database!

**Comment by donovaly** [comment]
I retested. I used a database created with OS 2.1, then a database created with OS 2.1 beta 1, then one created with OS 2.2 beta 2 and a new one created with beta 3.

It works with most databases, but not all. Take this simple database I created with beta 2:
[database-PDF-bug.zip](https://github.com/OpenSlides/OpenSlides/files/1959262/database-PDF-bug.zip)

With this one no PDF is output. I think it is a blocker because until we know why this happens, real life databases might be affected and getting the PDF for all motions is very important.

**Comment by emanuelschuetze** [comment]
I tested with your database:
The election PDF is not created because /media/file/logo-projector.png was not found - of course! You have to disable the pdf logo settings (go to "files" and deactivate the logo for pdf). Then you can create the election pdf successfully - also the ballot paper.
=> So not a bug. Please reopen if something fails.

**Comment by donovaly** [comment]
> logo-projector.png was not found - of course!
> So not a bug

I see this differently. Yes, the file is missing but OS is not telling me this so I am not lost. That OS is not giving feedback is a major problem in my experience:
- I had to create a ballot paper using Excel which was stressy and embarassing. A note from OS would have saved me lot of stress and negative feedback:
- During an assembly the admins are stressed. That an image file might be missing can happen, but remains in the memory of the audience is "crappy strange new software that is not yet ready". You know how people argue about new things - every bug is an argument against it.

I'll open a new bug issue because this is important in my opinion.
