### ISSUE TITLE
Cannot build angular_constants on new database

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3851]
When trying to create a new DB:
```
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_permission

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/home/finn/OpenSlides/OpenSlides/openslides/__main__.py", line 40, in main
    execute_from_command_line(sys.argv)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/finn/OpenSlides/OpenSlides/openslides/core/apps.py", line 45, in ready
    set_constants(get_constants_from_apps())
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/constants.py", line 16, in get_constants_from_apps
    out.update(get_angular_constants())
  File "/home/finn/OpenSlides/OpenSlides/openslides/users/apps.py", line 57, in get_angular_constants
    for permission in Permission.objects.all():
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/models/query.py", line 1183, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv37/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_permission
```

**Comment by jsaalfeld** [comment]
Way to reproduce:

    rm -rf OpenSlides
    git clone -b OpenSlides-3 https://github.com/OpenSlides/OpenSlides.git
    python3 -m venv .virtualenv
    source .virtualenv/bin/activate
    pip install -r requirements.txt
    python manage.py createsettings

**Comment by ostcar** [comment]
Could you test this in #3843

I think it should be fixed with that pr

**Comment by jsaalfeld** [comment]
Nope. Still broken. The same procedure leads to the same result.

**Comment by jsaalfeld** [comment]
With commit https://github.com/OpenSlides/OpenSlides/commit/8adaa6118a2bb0332680b5ada0a8a92bea99e0a5 the migrations and startup worked fine. It Broke with commit https://github.com/OpenSlides/OpenSlides/commit/732de97ec285fc1cf5e10ab082c1f5b374b4ca47.

**Comment by jsaalfeld** [comment]
PR #3855 fixes the issues.
